### ISSUE TITLE
IllegalStateException when milking a cow

### ISSUE THREAD

**Issue by Taschenmogul** [soultek101/projectzulu1.7.10#24]
I just confirmed a bug that was pointed out at:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2185602-better-overworld-project-zulu-1-7-10-mobs-blocks?comment=542

I cite:

> When you disable the Blocks module, or disable the wooden buckets, the game will crash whenever you try to milk a cow."

I am lazy so I will just post the piece of log below that I deem relevant.

```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:47)
    at com.stek101.projectzulu.common.core.EventHookContainerClass.onEntityInteract(EventHookContainerClass.java:191)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_480_EventHookContainerClass_onEntityInteract_EntityInteractEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1122)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:413)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1431)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

This is on Forge 10.13.4.1566, ProjectZulu 1.4c2 and Java 7 with several other mods installed.

**Comment by LavaSlayer** [comment]
This same crash occurs when feeding a cow with wheat.  Oddly enough, it does not crash the server in multiplayer.  Only the client crashes.
